skip_branch_with_pr: true

environment:
  matrix:
    - PYTHON: "C:\\Python36"
      TOXENV: "py36"

    - PYTHON: "C:\\Python37"
      TOXENV: "py37"

install:
  - "%PYTHON%/python.exe -m pip install -U pip"
  - "%PYTHON%/python.exe -m pip install -U tox"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - "%PYTHON%/Scripts/tox"

# We don't deploy anything on tags with AppVeyor, we use Travis instead, so we
# might as well save resources
skip_tags: true
