name: barril

dependencies:
  - python>=3.6
  - attrs>=18.1.0
  - numpy>=1.11.0
  - oop-ext>=0.2.4
  - pre_commit
  - pytest
  - pytest-mock>=1.10
  - black>=19.3b0
  - pre-commit>=1.11.0

environment:
  PYTHONPATH:
    - {{ root }}/src
